# libjnidispatch.so — the native half of JNA 5.14.0 (used by oshi and text2speech in
# Minecraft 1.21.x). Sources: native/dispatch.c + native/callback.c, linked with the
# same static libffi as liblwjgl.so (JNA 5.14.0 bundles libffi 3.4.4 too).
#
# The JNI headers (com_sun_jna_Native.h, com_sun_jna_Function.h) are generated by
# javac -h from the JNA Java sources, as JNA's own ant build does.
# Defines follow native/Makefile: the "android" target for Android
# (-DNO_JAWT -DNO_WEAK_GLOBALS, no HAVE_PROTECTION), the "linux" target for the host.

find_package(Java 1.8 COMPONENTS Development REQUIRED)

set(_jna "${NL_JNA_DIR}")
set(_jna_hdr "${CMAKE_BINARY_DIR}/jna-headers")
set(_jna_classes "${CMAKE_BINARY_DIR}/jna-classes")
file(GLOB_RECURSE _jna_java CONFIGURE_DEPENDS "${_jna}/src/com/sun/jna/*.java")

add_custom_command(
  OUTPUT "${_jna_hdr}/com_sun_jna_Native.h" "${_jna_hdr}/com_sun_jna_Function.h"
  COMMAND ${CMAKE_COMMAND} -E rm -rf "${_jna_hdr}" "${_jna_classes}"
  COMMAND ${CMAKE_COMMAND} -E make_directory "${_jna_hdr}" "${_jna_classes}"
  COMMAND "${Java_JAVAC_EXECUTABLE}" -nowarn -encoding UTF-8 -Xlint:none
          -h "${_jna_hdr}" -d "${_jna_classes}" ${_jna_java}
  DEPENDS ${_jna_java}
  COMMENT "javac -h: JNA ${JNA_VERSION} JNI headers"
  VERBATIM)
add_custom_target(nl_jna_headers DEPENDS "${_jna_hdr}/com_sun_jna_Native.h")

nl_shared_library(jnidispatch OUTPUT_NAME jnidispatch
  VERSION_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/cmake/jni.version.script")
target_sources(jnidispatch PRIVATE "${_jna}/native/dispatch.c" "${_jna}/native/callback.c")
add_dependencies(jnidispatch nl_jna_headers nl_libffi_build)
target_include_directories(jnidispatch PRIVATE "${_jna_hdr}" "${NL_LIBFFI_INCLUDE_DIR}")
target_compile_definitions(jnidispatch PRIVATE
  "JNA_JNI_VERSION=\"${JNA_JNI_VERSION}\""
  "CHECKSUM=\"${JNA_JNI_MD5}\""
  _REENTRANT
  NO_JAWT)
if(NL_HOST)
  target_compile_definitions(jnidispatch PRIVATE HAVE_PROTECTION)
else()
  target_compile_definitions(jnidispatch PRIVATE NO_WEAK_GLOBALS)
endif()
# Same warning set / aliasing rules as JNA's Makefile.
target_compile_options(jnidispatch PRIVATE -fno-omit-frame-pointer -fno-strict-aliasing
  -W -Wall -Wno-unused -Wno-parentheses)
target_link_libraries(jnidispatch PRIVATE nl_libffi ${CMAKE_DL_LIBS})
# Bind to our own static libffi even if another libffi is loaded in the process.
target_link_options(jnidispatch PRIVATE -Wl,-Bsymbolic)
